import type { RunLog } from '../log.js';
type Model = { key?: string; id?: string; type?: string; state?: string; loaded?: boolean };
const textFrom = (body: any) => body?.choices?.[0]?.message?.content ?? body?.output?.find((x: any) => x.type === 'message')?.content ?? body?.output_text;
export class LMStudioClient {
  constructor(private readonly settings: { baseUrl: string; token: string; primaryModel: string; allowFallbackLoad: boolean; timeoutMs: number; retryLimit: number }, private readonly log: RunLog) {}
  private async request(path: string, init: RequestInit = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.settings.timeoutMs); try { const response = await fetch(`${this.settings.baseUrl}${path}`, { ...init, signal: controller.signal, headers: { 'content-type': 'application/json', ...(this.settings.token ? { authorization: `Bearer ${this.settings.token}` } : {}), ...init.headers } }); if (!response.ok) throw new Error(`${init.method ?? 'GET'} ${path} returned ${response.status}: ${(await response.text()).slice(0, 500)}`); return response.json(); } finally { clearTimeout(timer); } }
  async health() { await this.request('/v1/models'); await this.log.write('lmstudio.health_ok', { base_url: this.settings.baseUrl }); }
  private async models(): Promise<Model[]> { const native = await this.request('/api/v1/models'); const openai = await this.request('/v1/models'); return [...(native.models ?? native.data ?? []), ...(openai.data ?? [])]; }
  private isLlm(model: Model) { return !model.type || model.type.toLowerCase() === 'llm'; }
  private key(model: Model) { return model.key ?? model.id ?? ''; }
  private async load(model: string) { const body = await this.request('/api/v1/models/load', { method: 'POST', body: JSON.stringify({ model }) }); if (body.type !== 'llm') throw new Error(`Refusing to load non-LLM model ${model}`); await this.log.write('lmstudio.model_loaded', { model }); return body.instance_id ?? model; }
  private async completion(model: string, prompt: string) { const body = await this.request('/v1/chat/completions', { method: 'POST', body: JSON.stringify({ model, temperature: 0.4, messages: [{ role: 'system', content: 'You write accurate, original WordPress blog articles. Never invent citations, sources, product claims, or technical facts.' }, { role: 'user', content: prompt }] }) }); const text = textFrom(body); if (typeof text !== 'string' || !text.trim()) throw new Error(`LM Studio returned no article text for ${model}`); return text.trim(); }
  async generate(prompt: string): Promise<{ markdown: string; model: string }> { await this.health(); const models = await this.models(); const llms = models.filter(m => this.isLlm(m) && this.key(m)); const primary = this.settings.primaryModel; const available = new Set(llms.map(m => this.key(m)));
    const candidates = [primary, ...llms.map(m => this.key(m)).filter(key => key !== primary)]; let last: unknown;
    for (const candidate of candidates) { if (candidate !== primary && !available.has(candidate)) continue; try { let model = candidate; if (!available.has(candidate) && candidate === primary) { await this.log.write('lmstudio.primary_not_listed', { model: candidate }); continue; } for (let attempt = 0; attempt <= this.settings.retryLimit; attempt++) { try { const markdown = await this.completion(model, prompt); await this.log.write('lmstudio.generation_succeeded', { model, attempt }); return { markdown, model }; } catch (error) { last = error; await this.log.write('lmstudio.generation_failed', { model, attempt, error: String(error) }); if (attempt === this.settings.retryLimit) break; } } if (candidate !== primary && this.settings.allowFallbackLoad) { model = await this.load(candidate); const markdown = await this.completion(model, prompt); return { markdown, model }; } } catch (error) { last = error; await this.log.write('lmstudio.model_failed', { model: candidate, error: String(error) }); } }
    throw new Error(`No LM Studio LLM completed generation. ${String(last ?? '')}`);
  }
}
