import { mkdir, open, rename, rm } from 'node:fs/promises';
import path from 'node:path';
import XLSX from 'xlsx';
import type { BlogRow, BlogStatus } from '../types.js';
const sheetName = 'Blog tracker'; const required = ['blog_id', 'blog_topic', 'blog_status', 'blog_created_date', 'blog_posted_date']; const iso = () => new Date().toISOString();
export class ExcelTracker {
  constructor(readonly file: string) {}
  private async lock<T>(work: () => Promise<T>): Promise<T> { const lock = `${this.file}.lock`; await mkdir(path.dirname(this.file), { recursive: true }); let handle; try { handle = await open(lock, 'wx'); return await work(); } finally { await handle?.close(); await rm(lock, { force: true }); } }
  private read() { const book = XLSX.readFile(this.file, { cellStyles: true }); const sheet = book.Sheets[sheetName]; if (!sheet) throw new Error(`Workbook must contain a sheet named "${sheetName}"`); const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: '' }); for (const key of required) if (!(key in (rows[0] ?? {}))) throw new Error(`Workbook is missing required column: ${key}`); return { book, sheet, rows }; }
  private async atomic(book: XLSX.WorkBook) { const temp = `${this.file}.${process.pid}.tmp.xlsx`; XLSX.writeFile(book, temp, { cellStyles: true }); XLSX.readFile(temp); await rename(temp, this.file); }
  async rows(): Promise<BlogRow[]> { const { rows } = this.read(); return rows.map((row, index) => ({ ...row, row: index + 2, blog_id: String(row.blog_id), blog_topic: String(row.blog_topic), blog_status: String(row.blog_status) as BlogStatus })); }
  async claimNext(): Promise<BlogRow | undefined> { return this.lock(async () => { const { book, sheet, rows } = this.read(); const index = rows.findIndex(row => String(row.blog_status).toLowerCase() === 'pending'); if (index < 0) return undefined; const row = index + 2; this.setCells(sheet, row, { blog_status: 'generating', review_status: 'pending', last_error: '', last_updated_at: iso() }); await this.atomic(book); return { ...rows[index], row, blog_id: String(rows[index].blog_id), blog_topic: String(rows[index].blog_topic), blog_status: 'generating' as BlogStatus }; }); }
  async update(blogId: string, changes: Record<string, string>) { return this.lock(async () => { const { book, sheet, rows } = this.read(); const index = rows.findIndex(row => String(row.blog_id) === String(blogId)); if (index < 0) throw new Error(`blog_id ${blogId} no longer exists in tracker`); this.setCells(sheet, index + 2, { ...changes, last_updated_at: iso() }); await this.atomic(book); }); }
  private setCells(sheet: XLSX.WorkSheet, row: number, changes: Record<string, string>) { const header = XLSX.utils.sheet_to_json<string[]>(sheet, { header: 1, blankrows: false })[0] ?? []; for (const [key, value] of Object.entries(changes)) { let col = header.indexOf(key); if (col < 0) { col = header.length; header.push(key); sheet[XLSX.utils.encode_cell({ r: 0, c: col })] = { t: 's', v: key }; const range = XLSX.utils.decode_range(sheet['!ref'] ?? 'A1'); range.e.c = Math.max(range.e.c, col); sheet['!ref'] = XLSX.utils.encode_range(range); } sheet[XLSX.utils.encode_cell({ r: row - 1, c: col })] = { t: 's', v: value }; } }
}
