import { existsSync } from 'node:fs';
import type { config as configFactory } from '../config/index.js';
import { requireWordPress } from '../config/index.js';
import { saveDraft, parseDraft, promptFor } from '../generation/blog.js';
import { LMStudioClient } from '../lmstudio/client.js';
import { parseReview, type DryRunMessageAdapter } from '../messaging/imessage.js';
import { RunLog } from '../log.js';
import { ExcelTracker } from '../tracker/excel.js';
import { WordPressClient } from '../wordpress/client.js';
import type { MessageAdapter } from '../types.js';
type Settings = ReturnType<typeof configFactory>;
export class BlogWorkflow {
  private readonly tracker: ExcelTracker; private readonly log: RunLog; private readonly lm: LMStudioClient;
  constructor(private readonly settings: Settings, private readonly messages: MessageAdapter, private readonly dryRun: boolean) { this.tracker = new ExcelTracker(settings.trackerPath); this.log = new RunLog(settings.runsDir); this.lm = new LMStudioClient(settings.lm, this.log); }
  private async notify(text: string, attachment?: string) { if (this.dryRun) return this.log.write('imessage.skipped_dry_run', { text, attachment }); await this.messages.send(text, attachment); await this.log.write('imessage.sent', { text, attachment }); }
  async processReviews() { const rows = (await this.tracker.rows()).filter(row => row.blog_status === 'awaiting_review'); if (!rows.length || this.dryRun) return 0; const replies = await this.messages.latestReplies(); let handled = 0; for (const reply of replies) { const decision = parseReview(reply.text); const row = decision && rows.find(candidate => candidate.blog_id === decision.blogId); if (!row || !decision) continue; if (decision.decision === 'rejected') { await this.tracker.update(row.blog_id, { blog_status: 'rejected', review_status: 'rejected', review_reply_at: reply.receivedAt }); await this.notify(`Blog draft #${row.blog_id} was rejected. No post was created.`); handled++; continue; } await this.tracker.update(row.blog_id, { blog_status: 'approved', review_status: 'approved', review_reply_at: reply.receivedAt }); await this.postApproved(row.blog_id); handled++; } return handled; }
  private async postApproved(blogId: string) { const row = (await this.tracker.rows()).find(candidate => candidate.blog_id === blogId); if (!row || row.blog_status === 'posted') return; if (!row.markdown_path || !existsSync(row.markdown_path)) { await this.tracker.update(blogId, { blog_status: 'error', last_error: 'Approved draft file is missing' }); await this.notify(`Blog #${blogId} could not be posted: the draft file is missing.`); return; } try { await this.tracker.update(blogId, { blog_status: 'posting', last_error: '' }); if (this.dryRun) { await this.log.write('wordpress.skipped_dry_run', { blog_id: blogId }); return; } const post = await new WordPressClient(requireWordPress(this.settings)).post(await parseDraft(row.markdown_path)); await this.tracker.update(blogId, { blog_status: 'posted', blog_posted_date: new Date().toISOString(), wordpress_post_id: String(post.id), wordpress_url: post.link }); await this.notify(`Blog #${blogId} was posted successfully: ${post.link}`); } catch (error) { await this.tracker.update(blogId, { blog_status: 'error', last_error: String(error) }); await this.notify(`Blog #${blogId} could not be posted: ${String(error)}`); throw error; } }
  async processNext() { await this.processReviews(); const row = await this.tracker.claimNext(); if (!row) { await this.log.write('workflow.no_pending_rows'); return; } try { await this.log.write('workflow.generation_started', { blog_id: row.blog_id }); const generated = await this.lm.generate(promptFor(row.blog_topic)); const draft = await saveDraft(this.settings.draftsDir, row, generated.markdown, generated.model); await this.tracker.update(row.blog_id, { blog_status: 'awaiting_review', review_status: 'pending', review_token: `YES ${row.blog_id} / NO ${row.blog_id}`, markdown_path: draft, model_used: generated.model, blog_created_date: new Date().toISOString(), last_error: '' }); await this.notify(`Blog draft #${row.blog_id} is ready: “${row.blog_topic}”\n\nReply exactly:\nYES ${row.blog_id} — post it to WordPress\nNO ${row.blog_id} — reject and stop`, draft); await this.log.write('workflow.awaiting_review', { blog_id: row.blog_id, draft, model: generated.model }); } catch (error) { await this.tracker.update(row.blog_id, { blog_status: 'error', last_error: String(error) }); await this.notify(`Blog #${row.blog_id} could not be generated: ${String(error)}`); throw error; } }
}
